✨ add Hangman
LouisaStrunk02/Hangman pull request #1
Opened 2022-10-18 06:43 UTC by LouisaStrunk02

Changes:

add a hangman game

2022-10-18 07:16 UTC, stefanluth requested changes

2022-10-18 07:16 UTC, stefanluth commented on Hangman.py
> +def printHangmanStages(stage):
Python uses snake_case for function names :)

2022-10-18 07:16 UTC, stefanluth commented on Hangman.py
> +    listOfLetters = [0] * remaining_tries
snake_case :)

2022-10-18 07:16 UTC, stefanluth commented on Hangman.py
> +                break
Does the word list include single letter "words"?

2022-10-18 07:16 UTC, stefanluth commented on HangmanStages.py
> +    ]
EOF

2022-10-19 12:47 UTC, DevBastiS approved these changes

2022-10-24 07:27 UTC, stefanluth commented on HangmanStages.py
> +                """,
Indentation is off :)

2022-10-25 12:54 UTC, shoreal approved these changes

2022-10-26 07:30 UTC, stefanluth approved these changes

2022-10-26 13:50 UTC, merged